version: '3.9'

services:
  myshop:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myshop:/myshop
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    env_file: example.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"






volumes:
  pg_data:
